### ISSUE TITLE
'car right'

### ISSUE THREAD

**Issue by Sandlot1927** [TheAmeliaMay/PartyBox#1]
when submitting 'far-right' for position, it has a typo for 'car right'
![image](https://github.com/TheAmeliaMay/PartyBox/assets/164722446/e4e5a1cd-2a34-44cc-bb05-96474b8f6696)

**Comment by TheAmeliaMay** [comment]
Thanks for telling me, I fixed it, but any links already created with the typo will still have it present (just change the URL if you have to).
